### ISSUE TITLE
Is there a typo in this route

### ISSUE THREAD

**Issue by Dashman99** [awatson1978/rest-api#5]
Hi Abigail,

I am new to meteor and iron-router, so forgive me if I'm way off.  Did you mean to route /api/find/post/:postId instead of /posts/:postId ?

Maybe it is a typo? 

// api:      http://localhost:3000/api/find/post/:postId
// example:  http://localhost:3000/api/find/post/314159
Router.route('/posts/:postId', function(){
  this.response.statusCode = 200;
  this.response.setHeader("Content-Type", "application/json");
  this.response.setHeader("Access-Control-Allow-Origin", "*");
  this.response.setHeader("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  this.response.end('Post contents... ' + JSON.stringify(
    Posts.findOne({_id: new Meteor.Collection.ObjectID(this.params.postId) })
  ));
}, {where: 'server'});

**Comment by Boo-urns** [comment]
Hi Dashman99 It seems that is the solution for the error. Once I altered the route the errors disappeared.

File located > server/rest/api.posts.js

**Comment by awatson1978** [comment]
Fixed by pull request #6.
